### ISSUE TITLE
Website 404

### ISSUE THREAD

**Issue by yaolion** [ongedit/chat-bubbles-for-youtube#3]
https://licitfree.github.io/chat-bubbles-for-youtube/

**Comment by cutbypham** [comment]
@yaolion thanks, Recently I change the GitHub username so it causes the issue here

The new domain name: https://thuantanphamfilms.github.io/chat-bubbles-for-youtube/

**Comment by brokenricefilms** [comment]
#5

**Comment by cutbypham** [comment]
duplicate #5
